### ISSUE TITLE
open file in finder when pressing cmd+enter

### ISSUE THREAD

**Issue by foss-** [ospfranco/sol#51] opened 2022-08-10 10:15 UTC
Most launcher allow to open a file in finder when pressing `cmd+enter` with a file selected from search results. Would be great if this was also possible with Sol.

**Comment by ospfranco** [comment] 2022-08-10 10:21
duplicate of #45

**Comment by ospfranco** [comment] 2022-08-22 07:28
Now that file search is there, this is valid

**Comment by ospfranco** [comment] 2022-08-23 06:20
Folder should now be open, selecting it in finder is another story though... I might have to resort to an AppleScript to do that, but I have to find time

**Closed** 2022-08-23 18:54 UTC
