### ISSUE TITLE
Usage of GitHub releases

### ISSUE THREAD

**Issue by SMillerDev** [ospfranco/sol#127] opened 2024-06-21 09:30 UTC
I'm a maintainer for Homebrew, and when working on some style issues in casks I found that this software embeds releases in the repo, which is highly unusual and probably pretty bad for git performance.
Would you consider adding the releases to the GitHub releases and tags so they are easier to find for people?

**Comment by ospfranco** [comment] 2024-06-21 10:43
hey, I think the releases folder was necessary for sparkle, can't remember. The homebrew listing was contributed in a PR so I don't really know how it works.

Moving to releases would be better indeed, but I'm going on vacation next week for 3 months, so I doubt I will get to it.

If you provide me with some docs I can try to take a look when I'm back.

**Comment by SMillerDev** [comment] 2024-06-21 11:10
Don't worry about the Homebrew part. Nothing is wrong there. Enjoy your holiday, here's an apidoc about release assets for when you return: https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28

**Comment by ospfranco** [comment] 2024-06-21 11:31
The problem is sparkle and the generation of the binaries. I have everything setup on my machine, because it is easy with notarization. Having to setup everything on github actions or even on my machine will be time consuming.

**Comment by ospfranco** [comment] 2024-10-04 10:20
I've recently migrated to using github releases with sparkle as well, this should be working now, though I'm not 100% sure I did not break anything.

**Comment by ospfranco** [comment] 2024-11-14 09:43
This seems to be working for now, at least on brew the latest version is being correctly fetched. Will close this. In case there are any issues just re-open it.

**Closed by ospfranco** 2024-11-14 09:43 UTC
